### ISSUE TITLE
Expected log was not created in the [channel_name] channel

### ISSUE THREAD

**Issue by DaaN88** [timacdonald/log-fake#46]
Hi. I am using Laravel 10.25.1.
And when i want test logging using your package, i get an error: `Expected log was not created in the [stderr_json] channel.
Failed asserting that false is true`.

Here's the code:
``` php
Log::channel(channel: 'stderr_json')->assertLogged(callback: function (LogEntry $log) {
          //dd($log);
          //$this->assertEquals(expected: 'stderr_json', actual: $log->channel);
      }
  );
```

But, when i am call dd(), i get the following:
``` php
TiMacDonald\Log\LogEntry^ {#1986 // tests/Feature/Clients/Exceptions/DomainNameCreationExceptionTest.php:98
  +level: "error"
  +message: """
     | Stack trace: #0 /src/vendor/phpunit/phpunit/src/Framework/TestCase.php(1102): Feature\Clients\Exceptions\DomainNameCreationExceptionTest->test_correctness_content_exception()\n
    #1 /src/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php(174): PHPUnit\Framework\TestCase->runTest()\n
    #2 /src/vendor/phpunit/phpunit/src/Framework/TestCase.php(653): Illuminate\Foundation\Testing\TestCase->runTest()\n
    #3 /src/vendor/phpunit/phpunit/src/Framework/TestRunner.php(103): PHPUnit\Framework\TestCase->runBare()\n
    #4 /src/vendor/phpunit/phpunit/src/Framework/TestCase.php(489): PHPUnit\Framework\TestRunner->run(Object(Feature\Clients\Exceptions\DomainNameCreationExceptionTest))\n
    #5 /src/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestCase->run()\n
    #6 /src/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()\n
    #7 /src/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()\n
    #8 /src/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()\n
    #9 /src/vendor/phpunit/phpunit/src/TextUI/Application.php(176): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))\n
    #10 /src/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run(Array)\n
    #11 {main}
    """
  +context: []
  +timesChannelHasBeenForgottenAtTimeOfWritingLog: 0
  +channel: "stderr_json"
}
```

What am I doing wrong, what could be the problem?

**Comment by timacdonald** [comment]
Can you please share the actual test snippet you are using in your tests?

**Comment by timacdonald** [comment]
It seems you aren't returning `true` from the closure.

**Comment by DaaN88** [comment]
Yes, you are right! :-) Thank's! (just add `return true` :-) )

But, in the readme there is no direct instruction to return `true` or I didn't see it.... And if there is nothing about true, maybe it should be added?

**Comment by timacdonald** [comment]
Hey, all the examples in the readme return a boolean, either `true` or `false`.

**Comment by DaaN88** [comment]
I understand, but in my first acquaintance with the package it was perceived as a simple assertion
